name: Update THM Badge

on:
  schedule:
    - cron: "*/5 * * * *" #runs every 5 minutes
  workflow_dispatch:
jobs:
  run-update-thm-badge-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # checkout the repository content to github runner.
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9' #install the python needed
      - run: python -m pip install --upgrade pip
      - run: ls -al
      - run: pip install -r requirements.txt
      - run: python update_thm_badge.py
      - run: ls -al
      - run: git status
      - run: git add .
      - run: git config user.email "thitareeudomsapaya@gmail.com"
      - run: git config user.name "github action auto-commit"
      - run: git commit -m "Auto updating THM Profile Badge"
      - run: git fetch origin main
      - run: git push origin HEAD:master
